name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"   # Update setiap hari jam 00:00 UTC
  workflow_dispatch:       # Bisa juga trigger manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Token gratis, tidak perlu setup
          USERNAME: ryanap7

      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          git commit -m "Generate 3D contribution calendar" || exit 0
          git push
